version: '3'
services:
    app:
        build:
            args:
                user: jonathan
                uid: 1000
            context: ./
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app
networks:
    laravel:
